#!/usr/bin/env python3
"""Derives the deterministic *reference visual fixture* envelopes from the approved PNG.

Only numeric per-column envelopes are extracted (extent above/below the trace centre, brightness); the editor's own
renderers draw everything. Output: Source/UI/ReferenceFixtureData.h (used only when the visual-test fixture is enabled)."""
import sys
from PIL import Image

REF = "references/playable-ambience-approved-gui.png"
im = Image.open(REF).convert("RGB")
px = im.load()

SYNC = (668, 180, 733, 212)  # the SYNC button floats over the delay well: never counted as signal

def warm(p, thr):
    r, g, b = p
    return r > thr and r > b + 35

def masked(x, y):
    return SYNC[0] <= x <= SYNC[2] and SYNC[1] <= y <= SYNC[3]

def column_extent(x, cy, y0, y1, thr=95):
    up = 0
    for y in range(cy, y0, -1):
        if not masked(x, y) and warm(px[x, y], thr): up = cy - y
    dn = 0
    for y in range(cy, y1):
        if warm(px[x, y], thr): dn = y - cy
    # brightness of the core (max luminance within +-2 px of centre)
    lum = max(sum(px[x, cy + d]) for d in range(-2, 3)) / 765.0
    return up, dn, lum

def delay():
    cy = 277
    out = []
    for x in range(42, 746):
        up, dn, lum = column_extent(x, cy, 172, 360)
        out.append((up, dn, lum))
    return out

def reverb():
    # per column: luminance-weighted vertical centre/spread of the particle cloud, and mean warmth
    out = []
    for x in range(791, 1495):
        tot = 0.0; ys = 0.0; y2 = 0.0; rsum = 0.0; bsum = 0.0
        for y in range(176, 364):
            r, g, b = px[x, y]
            l = max(0.0, (r + g + b) / 765.0 - 0.21)
            tot += l; ys += l * y; y2 += l * y * y; rsum += l * r; bsum += l * b
        if tot < 1e-6: out.append((0.0, 280.0, 0.0, 0.0)); continue
        mu = ys / tot; var = max(0.0, y2 / tot - mu * mu)
        out.append((tot, mu, var ** 0.5, (rsum - bsum) / (tot * 255.0)))
    return out

def harmony():
    lanes = {"G": 726, "Eb": 760, "C": 793}
    res = {}
    for name, cy in lanes.items():
        cols = []
        for x in range(42, 954):
            # trace centre: brightest pixel within +-9 px of the lane, extents of warm pixels within +-16
            best = max(range(cy - 9, cy + 10), key=lambda y: sum(px[x, y]))
            lum = sum(px[x, best]) / 765.0
            up = dn = 0
            for y in range(best, cy - 17, -1):
                if warm(px[x, y], 90): up = best - y
            for y in range(best, cy + 17):
                if warm(px[x, y], 90): dn = y - best
            cols.append((best - cy, up, dn, lum))
        res[name] = cols
    return res

def emit(path):
    d, r, h = delay(), reverb(), harmony()
    with open(path, "w") as f:
        f.write("// Generated by tools/visual/extract_fixture.py from references/playable-ambience-approved-gui.png.\n")
        f.write("// Numeric envelopes for the *reference visual fixture* only (visual-test mode); never used for live display.\n#pragma once\n\nnamespace pa::fixture\n{\n")
        f.write("// delay well columns x = 42..745: {extent above centre, extent below centre, core luminance}\n")
        f.write("inline constexpr float kDelay[%d][3] = {\n" % len(d))
        f.write(",\n".join("    { %d, %d, %.3ff }" % c for c in d) + "\n};\n")
        mx = max(c[0] for c in r) or 1.0
        f.write("// reverb well columns x = 791..1494: {energy 0..1, centre y, spread (sd px), warmth}\n")
        f.write("inline constexpr float kReverb[%d][4] = {\n" % len(r))
        f.write(",\n".join("    { %.4ff, %.1ff, %.2ff, %.3ff }" % (c[0] / mx, c[1], c[2], c[3]) for c in r) + "\n};\n")
        for name, cols in h.items():
            f.write("// harmony lane %s columns x = 42..953: {centre offset, extent up, extent down, core luminance}\n" % name)
            f.write("inline constexpr float kLane%s[%d][4] = {\n" % (name, len(cols)))
            f.write(",\n".join("    { %d, %d, %d, %.3ff }" % c for c in cols) + "\n};\n")
        f.write("} // namespace pa::fixture\n")

if __name__ == "__main__":
    emit(sys.argv[1] if len(sys.argv) > 1 else "Source/UI/ReferenceFixtureData.h")
